### ISSUE TITLE
Version conflict on `brunch new`

### ISSUE THREAD

**Issue by kavika13** [mutewinter/tapas-with-ember#26]
I run the command `brunch new gh:mutewinter/tapas-with-ember yarn-ember` according to the setup instructions. I am getting an error that there is a version conflict for handlebars.js

I think it is because the latest Ember.js uses handlebars.js 2.0.0, and tapas-with-ember specifies handlebars version 1.3.0

**Comment by mutewinter** [comment]
Oh yep, that's a problem I recently had to solve for a project. I'll push a fix for this soon. Thanks for filing this issue.

**Comment by kavika13** [comment]
Awesome. And thanks for the deprecation working in favor of ember-cli. It pushed me over the edge to figuring that tool out, and I'm already happier for it for Ember projects :)

**Comment by mutewinter** [comment]
Glad you liked that too :). It's definitely the path forward. Be sure to check out https://github.com/kimroen/ember-cli-coffeescript for coffeescript support.
